### ISSUE TITLE
debian build issue with X11_Xss_LIB

### ISSUE THREAD

**Issue by stefonarch** [lxqt/liblxqt#294]
Building LXQt on debian I stumpled into this:
```
-- Building liblxqt with Qt 5.15.2
-- 
-- liblxqt version: 0.17.0
-- 
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xss_LIB (ADVANCED)
    linked by target "lxqt" in directory /home/stef/git/lxqt/liblxqt

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```
<                                          --->
* Distribution & Version: debian 11 bullseye, git checkout
* Qt Version: 5.15.2
* libqtxdg Version: latest git
* lxqt-build-tools Version: latest git

**Comment by stefonarch** [comment]
Missed installing  libxss-dev, will update the wiki

**Comment by tsujan** [comment]
> Missed installing libxss-dev, will update the wiki

Pages like https://packages.debian.org/source/sid/liblxqt and https://packages.debian.org/sid/liblxqt0-dev may be helpful because they show all dependencies.

**Comment by stefonarch** [comment]
Actually the problem sat in front of the keyboard, didn't install all of the  mentioned packages in the wiki... 
[ Compiling with an i5 8th generation is very fast - I took a newer (used) labtop. ]
