### ISSUE TITLE
Feature request: support relative paths in wallpaper.cfg

### ISSUE THREAD

**Issue by stefonarch** [lxqt/liblxqt#302]
Add support for relative paths for wallpapers in wallper.cfg files in themes/<theme> dirs.

##### Possible Solution

Changes in https://github.com/lxqt/liblxqt/blob/08fff58a6d4aa9740d533d16f06b382fb1aa5858/lxqtsettings.cpp#L526

##### Context

Better use of common wallpapers directory, no symlink needed.
##### System Information

 Version: latest git.

**Comment by tsujan** [comment]
Good that you noticed it. I didn't know about that method.

Does this fix it?

```diff
diff -ruNp liblxqt-orig/lxqtsettings.cpp liblxqt/lxqtsettings.cpp
--- liblxqt-orig/lxqtsettings.cpp
+++ liblxqt/lxqtsettings.cpp
@@ -538,11 +538,11 @@ QString LXQtTheme::desktopBackground(int
 
     s.setArrayIndex(screen - 1);
     if (s.contains(QL1S("file")))
-        return QString::fromLatin1("%1/%2").arg(themeDir, s.value(QL1S("file")).toString());
+        return QDir::cleanPath(QString::fromLatin1("%1/%2").arg(themeDir, s.value(QL1S("file")).toString()));
 
     s.setArrayIndex(0);
     if (s.contains(QL1S("file")))
-        return QString::fromLatin1("%1/%2").arg(themeDir, s.value(QL1S("file")).toString());
+        return QDir::cleanPath(QString::fromLatin1("%1/%2").arg(themeDir, s.value(QL1S("file")).toString()));
 
     return QString();
 }

```

**Comment by stefonarch** [comment]
Works perfect, thanks!
With this we can get rid of symlinks for wallpapers.

**Comment by tsujan** [comment]
> With this we can get rid of symlinks for wallpapers.

Yes :)
