### ISSUE TITLE
2nd and farther submenu level automatically disappear not usable

### ISSUE THREAD

**Issue by ceever** [lxqt/liblxqt#317]
##### Expected Behavior
Any opened menu remains open until you select another submenu or click outside of the menu tree.

This is standard behaviour in MS WIndows.

##### Current Behavior
Whenever the mouse moves outside of the 2nd or higher menu level, everything is closed except for the first menu level.

This is especially frustrating with the "LXQt Settings" where it is not unlikely that the mouse moves outside the expanded (sub)menus before reaching the final menu.

Also, it is inconsistent that the first menu remains available and doesn't also close.

This also applies to PCmanFM-Qt menues.

![20230125 180803_rectangle_564x458](https://user-images.githubusercontent.com/40247591/214647833-802d33da-2549-476b-a2a5-facb7730d04d.png)

##### Possible Solution
Keep all expanded (sub)menus open until the user chooses another submenu or clicks somewhere outside the menu tree.

##### Steps to Reproduce (for bugs)
1. Click LXQt app menu
2. Choose "Preferences"
3. Choose "LXQt Setting"
4. Moving to the newly opened submenu with the mouse through the empty space that is not underlying any submenu

##### System Information
* PcManFm-qt version: 1.1.0
* Distribution & Version: Lubuntu 22.10
* Qt Version: 5.15.6
* liblxqt Version: ?

**Comment by tsujan** [comment]
Not reproducible.

What you see may be caused by the WM you use or something else, but it isn't done by LXQt.

**Comment by ceever** [comment]
I used a freshly downloaded and unmodified virgin Lubuntu 22.10 distribution.

Just open all submenus until the last of the LXQt Settings and move the mouse outside of the submenus area - all submenus except for the first app menu should close.

**Comment by tsujan** [comment]
> ... all submenus except for the first app menu should close.

Doesn't happen here. If the cursor has never gone over the last submenu, only the last submenu will be closed; otherwise, all submenus will remain open, including the last one.

Anyway, LXQt plays no role in this. Whether the behavior depends on the WM, the Qt style or something else is another question.

**Comment by stefonarch** [comment]
I can confirm this behaviour in Lubuntu 22.04 with openbox and in debian with xfwm4,  while with wayfire or kwin it doesn't happen apparently.

**Comment by ceever** [comment]
Yeah, diving into openbox currently. It got a specific parameter "submenuHideDelay", but changing it doesn't do anything. Maybe overwritten by the theme. 🤔

**Comment by tsujan** [comment]
@stefonarch, thanks for the tests! So, the WM controls it.

**Comment by ceever** [comment]
@tsujan , may I ask which window manager and display system you are using? Lubuntu comes with openbox on top of X11. I am wondering which causes this behaviour. Are there parameters for Qt where to manage such a behaviour?

**Comment by tsujan** [comment]
> which window manager and display system you are using?

Sometimes LXQt+kwin (X11), sometimes Wayfire+LXQt (Wayland).

>  I am wondering which causes this behaviour

As tests show, window managers control these things. I remember that I used compiz-reloaded with LXQt a year ago, and it had a worse problem with Qt menus. Since Openbox and compiz-reloaded aren't developed anymore, you could expect various problems in them.
