### ISSUE TITLE
Several files in liblxqt (mostly backlight-related code) is under GPL-2+, which cannot be converted to LGPL-2.1+

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/liblxqt#330]
See https://github.com/search?q=repo%3Alxqt%2Fliblxqt+%22gnu+general+public+license%22&type=code

liblxqt appears to be mostly under the LGPL-2.1+ license. However, there are several source code files (which can be seen in the above search query) that are licensed under GPL-2+. This means that liblxqt is effectively a GPL-2+ program, despite what the repository's license indicates, and that all software that links with it is also bound by GPL-2+.

It may be helpful to point this out so that no proprietary software attempts to use liblxqt. Alternatively, if this is unintentional, the GPL-2+ files should probably be relicensed.

**Comment by yan12125** [comment]
Backlight codes are first contributed in https://github.com/lxqt/liblxqt/pull/131. @selairi, mind to share about the reason for choosing GPL?

**Comment by selairi** [comment]
@yan12125 I relied on another code I had made to copy and paste the license. I thought it was the same license as liblxqt but now I see that I was wrong.

**Comment by yan12125** [comment]
Got it. How do you think about relicensing backlight codes you wrote to LGPL-2.1-or-later? Although I don't think any proprietary software will link to liblxqt, project management is easier with only one license.

**Comment by selairi** [comment]
There would be no problem. I'll change it.

**Comment by yan12125** [comment]
Should be fixed with https://github.com/lxqt/liblxqt/pull/335. After that, the whole liblxqt is `LGPL-2.1-or-later`.
