### ISSUE TITLE
FTBFS with Old KDE Frameworks

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/liblxqt#334]
When building 1.4 on a 22.04 system, which has KDE Frameworks 5.92, it FTBFS because in fae257647adc8729b597d9cf9617c81b99f9df42 the minimum was bumped to 5.101.

We're going to revert this commit for now, just in our Backports branch, but could we consider a conditional, in case some other systems use old Frameworks?

Thanks.

**Comment by tsujan** [comment]
> but could we consider a conditional

I think most LXQt devs agree that we should avoid conditionals as far as possible — as we do. Old systems can't be supported here.

**Comment by tsimonq2** [comment]
No worries, figured I'd bring it up regardless. Feel free to close if you feel that's appropriate, thanks.

**Comment by tsujan** [comment]
Thanks for your understanding!

Personally, I sometimes use several conditionals to support older systems, but that isn't feasible in LXQt (or in any team work with limited manpower).
